export const size=[1,2,3,4,4,5,6,6,1,2,2,3,4,4,5,5,6,6,7,7,8,8,9,9,9,7,2,6,6,1,5,5,4,4,4,4311]
export const type=["link1","link","link1","link","link1","link"]
export const options=["option1","option2","option3","option4","option1","option2","option3","option4","option5","option6"]
export const colors=[
{id:1,
name:"red",
value:"danger"
},
{id:2,
name:"green",
value:"success"
},
{id:3,
name:"black",
value:"dark"
},
{id:4,
name:"baby blue",
value:"info"
},
{id:5,
name:"yellow",
value:"warning"
},
{id:6,
name:"gray",
value:"secondary"
},
{id:7,
name:"blue",
value:"primary"
},
{id:8,
name:"wihte",
value:"light"
},
]
export const products = [
  {
    id: 1, 
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 44,
    color: "blue",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },
  {
    id: 2,
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 44,
    color: "blue",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },
  {
    id: 3,
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 4334,
    color: "red",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },
  {
    id: 1, 
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 44,
    color: "blue",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },
  {
    id: 2,
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 44,
    color: "blue",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },
  {
    id: 3,
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 4334,
    color: "red",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },

  {
    id: 1, 
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 44,
    color: "blue",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },
  {
    id: 2,
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 44,
    color: "blue",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },
  {
    id: 3,
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 4334,
    color: "red",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },

  {
    id: 1, 
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 44,
    color: "blue",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },
  {
    id: 2,
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 44,
    color: "blue",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },
  {
    id: 3,
    images: [
      {
        num: 1,
        src: 'https://images.pexels.com/photos/2850487/pexels-photo-2850487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        alt: 'First slide',
        size: ["m", 'l', 'xl', 'xxl'],
      },
      {
        num: 2,
        src: 'https://images.pexels.com/photos/9218538/pexels-photo-9218538.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Second slide',
        size: ["m", 'l'],
      },
      {
        num: 3,
        src: 'https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600',
        alt: 'Third slide',
        size: ["m", 'l', 'xl'],
      },
    ],
    productname: "dress",
    productdescription: "bla bla bla",
    price: 4334,
    color: "red",
    brand: "blabla",
    arrivals: "blabla",
    specialOffers: true,
    occasions: "blabla",
    style: "blabla",
  },

];
